### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by alishsan** [seanjparker/chess#2]
After successfully executing ./create-chess, I am getting the following error:
```
Exception in thread "main" java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at chess.core.display.Chessboard.initChessboard(Chessboard.java:63)
	at chess.core.display.GUIHandler.<init>(GUIHandler.java:25)
	at chess.core.Chess.main(Chess.java:28)
```

**Comment by seanjparker** [comment]
Hi @alishsan,

Thank you for pointing this out, I pushed a fix to the `master` branch.
You should be able to launch it using the steps (to be performed in the root directory of the project):

1. `$ rm -r bin`
2. `$ ./create-chess`
3. `$ java -jar Chess.jar`

**Comment by alishsan** [comment]
Thanks Sean! Appreciate it!

Alisher
